<?php

namespace App\Services;

use Spatie\Permission\Models\Permission;

class PermissionService extends BaseService
{

    public function __construct(Permission $model)
    {
        $this->model = $model;
    }

    public function getAll($where = [])
    {
        $permissions = parent::getAll($where); // TODO: Change the autogenerated stub
        return $permissions->map(function ($permission) {
            return [
                'id' => $permission->id,
                'name' => $permission->name,
            ];
        });
    }

}
