<?php

namespace App\Services;

use App\Http\Requests\Auth\SendOTPRequest;
use App\Mail\OTPVerificationMail;
use App\Models\Code;
use App\Models\User;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Hash;

class UserService extends BaseService
{
    protected $mail;

    public function __construct(User $model, OTPVerificationMail $mail)
    {
        $this->model = $model;
        $this->mail = $mail;
    }


    public function create($data)
    {
        $user = parent::create($data); // TODO: Change the autogenerated stub
        $this->mail->sendEmail($user);
        return $user;
    }

    public function getAll($where = [])
    {
        if (\request()->route()->getPrefix() == 'user_api') {
            $user = \auth('user')->user();
            $where = [['id', '!=', $user->id]];
        }
        return parent::getAll($where); // TODO: Change the autogenerated stub
    }
}
